import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { clientName, providerToken } = await req.json();

    if (!providerToken) {
      throw new Error('Google OAuth providerToken is required to access Docs');
    }

    // 1. Create a new Google Document
    const createDocRes = await fetch('https://docs.googleapis.com/v1/documents', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${providerToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: `Master Services Agreement - ${clientName}`,
      })
    });

    if (!createDocRes.ok) {
      throw new Error(`Docs API error: ${await createDocRes.text()}`);
    }

    const docData = await createDocRes.json();
    const documentId = docData.documentId;

    // 2. Insert text into the Document
    const requests = [
      {
        insertText: {
          location: { index: 1 },
          text: `MASTER SERVICES AGREEMENT\n\nThis Master Services Agreement ("Agreement") is made between Cadence and ${clientName}.\n\n1. SERVICES PROVIDED\nCadence agrees to provide the services as outlined in subsequent Statements of Work.\n\n2. PAYMENT TERMS\nClient agrees to pay all invoices within Net 30 days of receipt, unless otherwise specified.\n\n3. CONFIDENTIALITY\nBoth parties agree to maintain strict confidentiality of all proprietary information.\n\n[DRAFT GENERATED BY CADENCE AI]`
        }
      }
    ];

    await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${providerToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ requests })
    });

    return new Response(JSON.stringify({ 
      success: true, 
      docUrl: `https://docs.google.com/document/d/${documentId}/edit`
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
