import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { clientId, clientName, providerToken } = await req.json();

    if (!providerToken) {
      throw new Error('Google OAuth providerToken is required to access Drive');
    }

    // Initialize Supabase to fetch client data
    const supabaseUrl = Deno.env.get('SUPABASE_URL') || '';
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Fetch Contracts
    const { data: contracts } = await supabase
      .from('contracts')
      .select('*, contract_terms(*), contract_findings(*)')
      .eq('client_id', clientId)
      .eq('status', 'complete');

    // Fetch Invoices
    const { data: invoices } = await supabase
      .from('invoices')
      .select('*, invoice_analysis(*)')
      .eq('client_id', clientId)
      .order('created_at', { ascending: false });

    // Format Data to string
    let reportText = `${clientName} - Master Financial Report\nGenerated by Cadence\n\n`;
    
    reportText += `--- CONTRACTS ---\n`;
    if (contracts && contracts.length > 0) {
      contracts.forEach((c) => {
        reportText += `\nContract: ${c.file_name}\n`;
        reportText += `Terms extracted:\n`;
        c.contract_terms.forEach((t: any) => {
          reportText += `  - ${t.term_key.replace('_', ' ')}: ${t.edited_value || t.term_value}\n`;
        });
        reportText += `AI Findings:\n`;
        c.contract_findings.forEach((f: any) => {
          reportText += `  - [${f.severity.toUpperCase()}] ${f.title}: ${f.description}\n`;
        });
      });
    } else {
      reportText += `No processed contracts found.\n`;
    }

    reportText += `\n--- INVOICES ---\n`;
    if (invoices && invoices.length > 0) {
      invoices.forEach((inv) => {
        reportText += `\nInvoice #${inv.invoice_number || 'N/A'}\n`;
        reportText += `Amount: $${inv.amount.toLocaleString()}\n`;
        reportText += `Due Date: ${inv.due_date}\n`;
        reportText += `Status: ${inv.payment_status}\n`;
        
        if (inv.invoice_analysis && inv.invoice_analysis.length > 0) {
          const analysis = inv.invoice_analysis[0];
          reportText += `AI Risk Level: ${analysis.risk_level.toUpperCase()}\n`;
          reportText += `AI Advice: ${analysis.explanation}\n`;
        }
      });
    } else {
      reportText += `No invoices found.\n`;
    }

    // 1. Create a Folder for the client
    const folderMetadata = {
      name: `Cadence - ${clientName || 'General'}`,
      mimeType: 'application/vnd.google-apps.folder',
    };

    const createFolderRes = await fetch('https://www.googleapis.com/drive/v3/files', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${providerToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(folderMetadata)
    });

    if (!createFolderRes.ok) {
      throw new Error(`Drive API error: ${await createFolderRes.text()}`);
    }

    const folderData = await createFolderRes.json();
    const folderId = folderData.id;

    // 2. Create the Google Doc inside the folder
    const docMetadata = {
      name: `${clientName} - Master Financial Report`,
      mimeType: 'application/vnd.google-apps.document',
      parents: [folderId]
    };

    const createDocRes = await fetch('https://www.googleapis.com/drive/v3/files', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${providerToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(docMetadata)
    });

    if (!createDocRes.ok) {
      throw new Error(`Drive Docs creation error: ${await createDocRes.text()}`);
    }

    const docData = await createDocRes.json();

    // 3. Insert the report text into the Document using Google Docs API
    const requests = [
      {
        insertText: {
          location: { index: 1 },
          text: reportText
        }
      }
    ];

    const updateRes = await fetch(`https://docs.googleapis.com/v1/documents/${docData.id}:batchUpdate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${providerToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ requests })
    });

    if (!updateRes.ok) {
      throw new Error(`Docs Update error: ${await updateRes.text()}`);
    }

    return new Response(JSON.stringify({ 
      success: true, 
      folderUrl: `https://drive.google.com/drive/folders/${folderId}`,
      docUrl: `https://docs.google.com/document/d/${docData.id}/edit`
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
